### ISSUE TITLE
Bug19 mirgration static to dynamic

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-feed#11]
original bug: https://github.com/zendframework/zend-feed/issues/19

---

Originally posted by @necromant2005 at https://github.com/zendframework/zend-feed/pull/23

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.

**Comment by froschdesign** [comment]
@alexmerlin 
It is a bad idea to close issues when they are a part of a milestone. Either remove the milestone or leave the issues open.

In this repository the issues are still relevant for the next major version, so please do not close it!

**Comment by alexmerlin** [comment]
> @alexmerlin It is a bad idea to close issues when they are a part of a milestone. Either remove the milestone or leave the issues open.
> 
> In this repository the issues are still relevant for the next major version, so please do not close it!

Gotcha! 👍
