### ISSUE TITLE
Remove Reader\AbstractEntry, Reader\AbstractFeed, Reader\Collection

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-feed#2]
Related to #97 

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-feed/issues/103

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
(Activity from the 14th of August 2023 is not real - it's GitHub interpreting a comment with `#2` in it as a reference to this issue.)
