### ISSUE TITLE
itunes:explicit values have changed

### ISSUE THREAD

**Issue by OpenHaus** [laminas/laminas-feed#20]
### Bug Report

The values for the itunes:explicit tag on channel and episode level changed to "true/false".

|    Q        |   A
|------------ | ------
| Version(s)  | 2.12.2

#### Summary

According to Apple´s documentation the values for the itunes:explicit tag on channel and episode level are not "yes/clean" anymore but now "true/false".

> <itunes:explicit> 
> 
> The podcast parental advisory information.The explicit value can be one of the following:true. 
> 
> If you specify **true**, indicating the presence of explicit content, Apple Podcasts displays an Explicit parental advisory graphic for your podcast.Podcasts containing explicit material aren’t available in some Apple Podcasts territories.
> 
> If you specify **false**, indicating that your podcast doesn’t contain explicit language or adult content, Apple Podcasts displays a Clean parental advisory graphic for your podcast.

See: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

#### Current behavior

To mark a channel or episode as explicit "yes" is used. To mark a channel or episode as not explicit "clean" is used.

#### How to reproduce

Generate a feed with channel or an episode set as explicit.

#### Expected behavior

A channel or episode marked as explicit should have the value `<itunes:explicit>true</itunes:explicit>`.
A channel or episode marked as clean / not explicit should have the value `<itunes:explicit>false</itunes:explicit>`.

**Comment by froschdesign** [comment]
@OpenHaus 
Very good catch! Thanks for reporting the problem. I will create a for it.

**Comment by psil67** [comment]
Apparently the values have changed again. The RSS feed of Wordpress produces
true/false
which is incorrect according to the RSS validator which says it should be
[line 36](https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fphilippesilberzahn.com%2Fcategory%2Fpodcast%2Ffeed%2F#l36), column 22: itunes:explicit must be "yes", "no", or "clean": false [[help](https://www.rssboard.org/rss-validator/docs/error/InvalidYesNoClean.html)]

**Comment by froschdesign** [comment]
@psil67 
WordPress does not use this package (laminas-feed). Therefore, your problem has landed in the wrong place.
