### ISSUE TITLE
Replace usage of deprecated libxml_disable_entity_loader()

### ISSUE THREAD

**Issue by andypost** [laminas/laminas-feed#24]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

`libxml_disable_entity_loader()` is deprecated in PHP 8.0 https://github.com/php/php-src/commit/e0fa48f69dd14b52c8f1b2904ac7bd30472849a8 

It's used https://github.com/laminas/laminas-feed/blob/2.13.x/src/Reader/Reader.php

**Comment by alexpott** [comment]
See #25 - it's not a BC break and it's not a new feature.

**Comment by andypost** [comment]
Fixed with https://github.com/laminas/laminas-feed/pull/29
