### ISSUE TITLE
CRLF in vendor/laminas/laminas-feed/CHANGELOG.md

### ISSUE THREAD

**Issue by zhouhana** [laminas/laminas-feed#48]
The file CHANGELOG.md uses CRLF line endings. When I run a Drupal nstallation with Composer, I always get this warning (no other warnings from any other plugins):

warning: CRLF will be replaced by LF in vendor/laminas/laminas-feed/CHANGELOG.md.

The Composer installation uses 2.15.x but I tested the latest 2.17.x version and it still has CRLF line endings.

I don't know if I should count this as a bug but it seems odd that this file alone triggers this warning.

**Comment by Ocramius** [comment]
IMO we can just drop `CHANGELOG.md`: please send a patch

**Comment by zhouhana** [comment]
I don't know how to send a patch. I hope that someone else can do it.

**Comment by Ocramius** [comment]
Opened https://github.com/laminas/laminas-feed/pull/49

**Comment by Ocramius** [comment]
Should be fixed in `2.17.0`

**Comment by zhouhana** [comment]
Wow, you're quick! Thanks.
