### ISSUE TITLE
Error 500 when rendering a feed with some set*() methods

### ISSUE THREAD

**Issue by ErnadoO** [laminas/laminas-feed#61]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.18.1

#### Summary

Hello,

When I call setItunesEpisode(), i got this errror:

![image](https://user-images.githubusercontent.com/6375756/183459644-817a4ce1-4d44-489f-bd0d-85fca22afb32.png)

Since This [PR](https://github.com/laminas/laminas-feed/pull/57), `declare(strict_types=1);` was added and broke some pieces of code when argument of createTextNode() is not a string. Same behavior with setItunesSeason() (and maybe others)

#### Previous behavior

All good with v2.17, i can render an RSS feed with iTunes attributes.

#### Current behavior

Error 500, because of a wrong parameter type.

#### How to reproduce

Just Write a simple feed :

        $feed = new \Laminas\Feed\Writer\Feed ();

        $feed->setTitle('Serie Name')
            ->setDescription('Description')
            ->setLink('https//www.example.com');

        $item = $feed->createEntry();
        $item->setTitle('Episode Title')
            ->setItunesEpisode(3);

        $feed->addEntry($item);

        $feed->export('rss');

**Comment by Ocramius** [comment]
Handled in #62

**Comment by ErnadoO** [comment]
Thanks
