### ISSUE TITLE
Add support for laminas/laminas-servicemanager 4.0 so this library can be used on PHP 8.2 + psr/container 2.0.

### ISSUE THREAD

**Issue by MegaChriz** [laminas/laminas-feed#75]
I maintain a Drupal module called "Feeds". Wit that module you can import content on a Drupal site. It uses laminas/laminas-feed to parse RSS feeds.

The issue is that Feeds cannot be installed currently on Drupal 10 + PHP 8.2 because Drupal 10 requires psr/container ~2.0.2 and only laminas/laminas-servicemanager 4.0.x is compatible with PHP 8.2 + psr/container ~2.0.2. (For some reason though laminas/laminas-servicemanager 3.15 _is_ compatible with psr/container 2.0.2 too, but not with PHP 8.2, hence the reason why my module is installable on Drupal 10 + PHP 8.1.)

Anyway, it would help if this project can declare a compatibility with laminas/laminas-servicemanager ^4.0.

See also https://www.drupal.org/project/feeds/issues/3325568

**Comment by froschdesign** [comment]
@MegaChriz 
> (For some reason though laminas/laminas-servicemanager 3.15 _is_ compatible with psr/container 2.0.2 too

This was a mistake; more here: https://github.com/laminas/laminas-servicemanager/pull/147

> Anyway, it would help if this project can declare a compatibility with laminas/laminas-servicemanager ^4.0.

Version 4 of laminas-servicemanager has not yet been released. Only two pre-releases: https://github.com/laminas/laminas-servicemanager/releases

**Comment by froschdesign** [comment]
@gsteel 
laminas-servicemanager was added as hard dependency here: https://github.com/laminas/laminas-feed/commit/d910177540e158e6daf623eec200a31ddbd1ce66 (#57)
Two problems arise from this:

1. The standalone extension manager are useless duplications ([reader](https://github.com/laminas/laminas-feed/blob/4efdf913e7bb93310f9afd5d4267cba170e2c165/src/Reader/StandaloneExtensionManager.php#L18) and [writer](https://github.com/laminas/laminas-feed/blob/4efdf913e7bb93310f9afd5d4267cba170e2c165/src/Writer/StandaloneExtensionManager.php#L15))
2. The component is pinned to version 1.0 of the PSR container interface

Any idea how we can solve the dependency?

**Comment by gsteel** [comment]
The only way to avoid getting pinned to container:1 is, as you mentioned, the un-released service manager v4, or, dropping the hard dependency on service manager.

I've added a patch which does the latter in #76 - if that works, we can release a minor yes?

**Comment by Ocramius** [comment]
Closing here, handled in #76
