### ISSUE TITLE
Laminas\Feed\Reader\ExtensionManagerInterface is said to be deprecated, but it still looks like to be required

### ISSUE THREAD

**Issue by MegaChriz** [laminas/laminas-feed#85]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.22.0

#### Summary

In my project I have a custom Extension manager class implemented that implements both Laminas\Feed\Reader\ExtensionManagerInterface and Laminas\Feed\Writer\ExtensionManagerInterface.

When running _phpstan_, I get the warning that these interfaces are deprecated. But on further inspection of the code, I see that these interfaces are still actively used in the codebase:
- `Laminas\Feed\Reader\Reader::setExtensionManager()` requires an instance of Laminas\Feed\Reader\ExtensionManagerInterface. This is a method that I'm calling, passing my custom extension manager.
- `Laminas\Feed\Writer\Writer::setExtensionManager()` requires an instance of Laminas\Feed\Writer\ExtensionManagerInterface.

I did not write the custom extension manager myself, the code comments say it is used as a bridge between the Laminas service manager to the Symfony container.
See https://git.drupalcode.org/project/feeds/-/blob/8.x-3.x/src/Component/ZfExtensionManagerSfContainer.php?ref_type=heads

Here is the code where the extension manager gets passed:
https://git.drupalcode.org/project/feeds/-/blob/8.x-3.x/src/Feeds/Parser/SyndicationParser.php?ref_type=heads#L76

If I don't pass the custom extension manager, then the following errors occur:
> Laminas\Feed\Reader\Exception\RuntimeException: Could not load extension "GeoRSS" using Plugin Loader. Check prefix paths are configured and extension exists.
> Laminas\Feed\Reader\Exception\RuntimeException: Could not load extension "MediaRSS" using Plugin Loader. Check prefix paths are configured and extension exists.

These two extensions are listed as a Symfony service currently.

#### Current behavior
- `Laminas\Feed\Reader\Reader::setExtensionManager()` requires an instance of a deprecated interface called Laminas\Feed\Reader\ExtensionManagerInterface.
- `Laminas\Feed\Writer\Writer::setExtensionManager()` requires an instance of a deprecated interface called Laminas\Feed\Writer\ExtensionManagerInterface.

#### How to reproduce
- Try to call `Laminas\Feed\Reader\Reader::setExtensionManager()` to pass something that does not implement the deprecated interface.
- Try to call `Laminas\Feed\Writer\Writer::setExtensionManager()` to pass something that does not implement the deprecated interface.

#### Expected behavior
I'm not sure what the expected behavior should be, because I don't know the reason why Laminas\Feed\Reader\ExtensionManagerInterface and Laminas\Feed\Writer\ExtensionManagerInterface got deprecated.

**Comment by froschdesign** [comment]
> But on further inspection of the code, I see that these interfaces are still actively used in the codebase:

Correct, because we can only change a method signature with a major version. But deprecations allow us to inform the user at an early stage.

We follow [semantic versioning](https://semver.org/):

> Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

**Comment by MegaChriz** [comment]
Okay, then I don't know yet how to transition to the new API. I would think that the Reader and Writer classes should have an alternative method for setting the extension manager that doesn't require the deprecated interface, to make it possible to remove the usage of the deprecated interface now. But I'm not a deprecation expert.

Or perhaps there is an other way to register extensions and calling `setExtensionManager()` with a custom extension manager is no longer supported? Is there documentation available that suggests how to remove the usage of the deprecated interface?

**Comment by froschdesign** [comment]
Deprecation does not mean there _must_ be an alternative and you can configure PHPStan or Pslam to handle the problem, we do the same:

https://github.com/laminas/laminas-feed/blob/ce1eb3844db7c4267c79afd05dcaebe3d5bfb635/psalm-baseline.xml#L1698-L1701

More changes will come with the support of version 4 of laminas-servicemanager – the dependency injection container of Laminas.

**Comment by MegaChriz** [comment]
You mean that you can ignore the deprecation for now? But I think that there's no way as of now to be compatible with two major versions of laminas-feed?

**Comment by froschdesign** [comment]
> You mean that you can ignore the deprecation for now?

Correct, it is only information that indicates future changes. Check the configuration option of PHPStan for this topic.
